### ISSUE TITLE
Add a licence

### ISSUE THREAD

**Issue by Groctel** [ElMagnificoPro/milton#1]
Great project! Remember to add a licence to protect your work. If this is the first timw you do this, click the "Add file" button in the GitHub interface and start by naming the file "LICENCE". GitHub will offer you a menu to review and select a licence from a list :)

**Comment by ElMagnificoPro** [comment]
Hey, thanks for the reminder, also glad that you enjoyed it ^^,
I actually thought I added the licence when creating the repo, dk why it wasn't added, anyway thanks
